# Code for the purpose of collecting all packages and version utilized in the stem article


library(tradeSeq)
library(RColorBrewer)
library(SingleCellExperiment)
library(slingshot)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyverse)
library(Seurat)
library(SingleCellExperiment)
library(dynfeature)
library(dynplot)
library(dynwrap)

sessionInfo()



# Install necessary helper packages
if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")

# CRAN Packages
remotes::install_version("dynwrap", version = "1.2.4")
remotes::install_version("dynplot", version = "1.1.2")
remotes::install_version("dynfeature", version = "1.0.1")
remotes::install_version("Seurat", version = "5.0.1")
remotes::install_version("SeuratObject", version = "5.0.1")
remotes::install_version("sp", version = "2.1-3")
remotes::install_version("lubridate", version = "1.9.3")
remotes::install_version("forcats", version = "1.0.0")
remotes::install_version("stringr", version = "1.5.1")
remotes::install_version("purrr", version = "1.0.2")
remotes::install_version("readr", version = "2.1.5")
remotes::install_version("tidyr", version = "1.3.1")
remotes::install_version("tibble", version = "3.2.1")
remotes::install_version("tidyverse", version = "2.0.0")
remotes::install_version("dplyr", version = "1.1.4")
remotes::install_version("ggplot2", version = "3.4.4")
remotes::install_version("princurve", version = "2.1.6")
remotes::install_version("RColorBrewer", version = "1.1-3")
remotes::install_version("RcppAnnoy", version = "0.0.22")
remotes::install_version("later", version = "1.3.2")
remotes::install_version("bitops", version = "1.0-7")
remotes::install_version("polyclip", version = "1.10-6")
remotes::install_version("fastDummies", version = "1.7.3")
remotes::install_version("lifecycle", version = "1.0.4")
remotes::install_version("processx", version = "3.8.3")
remotes::install_version("globals", version = "0.16.2")
remotes::install_version("lattice", version = "0.22-5")
remotes::install_version("MASS", version = "7.3-60.0.1")
remotes::install_version("magrittr", version = "2.0.3")
remotes::install_version("plotly", version = "4.10.4")
remotes::install_version("yaml", version = "2.3.8")
remotes::install_version("remotes", version = "2.4.2.1")
remotes::install_version("httpuv", version = "1.6.14")
remotes::install_version("sctransform", version = "0.4.1")
remotes::install_version("reticulate", version = "1.35.0")
remotes::install_version("cowplot", version = "1.1.3")
remotes::install_version("pbapply", version = "1.7-2")
remotes::install_version("abind", version = "1.4-5")
remotes::install_version("Rtsne", version = "0.17")
remotes::install_version("ggraph", version = "2.1.0")
remotes::install_version("RCurl", version = "1.98-1.14")
remotes::install_version("tweenr", version = "2.0.2")
remotes::install_version("ggrepel", version = "0.9.5")
remotes::install_version("irlba", version = "2.3.5.1")
remotes::install_version("listenv", version = "0.9.1")
remotes::install_version("fitdistrplus", version = "1.1-11")
remotes::install_version("parallelly", version = "1.36.0")
remotes::install_version("leiden", version = "0.4.3.1")
remotes::install_version("codetools", version = "0.2-19")
remotes::install_version("ggforce", version = "0.4.1")
remotes::install_version("tidyselect", version = "1.2.0")
remotes::install_version("farver", version = "2.1.1")
remotes::install_version("viridis", version = "0.6.5")
remotes::install_version("jsonlite", version = "1.8.8")
remotes::install_version("tidygraph", version = "1.3.1")
remotes::install_version("ellipsis", version = "0.3.2")
remotes::install_version("progressr", version = "0.14.0")
remotes::install_version("ggridges", version = "0.5.6")
remotes::install_version("survival", version = "3.5-7")
remotes::install_version("foreach", version = "1.5.2")
remotes::install_version("ica", version = "1.0-3")
remotes::install_version("Rcpp", version = "1.0.12")
remotes::install_version("glue", version = "1.7.0")
remotes::install_version("gridExtra", version = "2.3")
remotes::install_version("ranger", version = "0.16.0")
remotes::install_version("mgcv", version = "1.9-1")
remotes::install_version("withr", version = "3.0.0")
remotes::install_version("fastmap", version = "1.1.1")
remotes::install_version("GA", version = "3.2.4")
remotes::install_version("digest", version = "0.6.34")
remotes::install_version("R6", version = "2.5.1")
remotes::install_version("colorspace", version = "2.1-0")
remotes::install_version("scattermore", version = "1.2")
remotes::install_version("utf8", version = "1.2.4")
remotes::install_version("data.table", version = "1.15.0")
remotes::install_version("graphlayouts", version = "1.1.0")
remotes::install_version("httr", version = "1.4.7")
remotes::install_version("htmlwidgets", version = "1.6.4")
remotes::install_version("uwot", version = "0.1.16")
remotes::install_version("pkgconfig", version = "2.0.3")
remotes::install_version("gtable", version = "0.3.4")
remotes::install_version("lmtest", version = "0.9-40")
remotes::install_version("htmltools", version = "0.5.7")
remotes::install_version("scales", version = "1.3.0")
remotes::install_version("rstudioapi", version = "0.15.0")
remotes::install_version("reshape2", version = "1.4.4")
remotes::install_version("nlme", version = "3.1-164")
remotes::install_version("zoo", version = "1.8-12")
remotes::install_version("KernSmooth", version = "2.23-22")
remotes::install_version("pillar", version = "1.9.0")
remotes::install_version("vctrs", version = "0.6.5")
remotes::install_version("RANN", version = "2.6.1")
remotes::install_version("promises", version = "1.2.1")
remotes::install_version("xtable", version = "1.8-4")
remotes::install_version("cluster", version = "2.1.6")
remotes::install_version("cli", version = "3.6.2")
remotes::install_version("rlang", version = "1.1.3")
remotes::install_version("crayon", version = "1.5.2")
remotes::install_version("plyr", version = "1.8.9")
remotes::install_version("stringi", version = "1.8.3")
remotes::install_version("viridisLite", version = "0.4.2")
remotes::install_version("Matrix", version = "1.6-5")
remotes::install_version("hms", version = "1.1.3")
remotes::install_version("patchwork", version = "1.2.0")
remotes::install_version("future", version = "1.33.1")
remotes::install_version("statmod", version = "1.5.0")
remotes::install_version("shiny", version = "1.8.0")
remotes::install_version("ROCR", version = "1.0-11")
remotes::install_version("igraph", version = "2.0.1.1")
remotes::install_version("RcppParallel", version = "5.1.7")

# Bioconductor Packages
BiocManager::install("slingshot", version = "2.10.0")
BiocManager::install("TrajectoryUtils", version = "1.10.1")
BiocManager::install("SingleCellExperiment", version = "1.24.0")
BiocManager::install("SummarizedExperiment", version = "1.32.0")
BiocManager::install("Biobase", version = "2.62.0")
BiocManager::install("GenomicRanges", version = "1.54.1")
BiocManager::install("GenomeInfoDb", version = "1.38.5")
BiocManager::install("IRanges", version = "2.36.0")
BiocManager::install("S4Vectors", version = "0.40.2")
BiocManager::install("BiocGenerics", version = "0.48.1")
BiocManager::install("MatrixGenerics", version = "1.14.0")
BiocManager::install("zlibbioc", version = "1.48.0")
BiocManager::install("XVector", version = "0.42.0")
BiocManager::install("DelayedArray", version = "0.28.0")
BiocManager::install("SparseArray", version = "1.2.3")
BiocManager::install("S4Arrays", version = "1.2.0")
BiocManager::install("tradeSeq", version = "1.16.0")


